allowed_argv = ["help",
                "filename",
                "lone",
                "--path",
                "--destine", 
                "--img",
                "--music",
                "--video",
                "--doc",
                "--custom",
                "-h",
                "-p",
                "-d",
                "-i",
                "-m",
                "-v",
                "-d",
                "-c"]